// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void PouringAnimation_Animation( lv_obj_t *TargetObject, int delay);

// SCREEN: ui_Loading
void ui_Loading_screen_init(void);
extern lv_obj_t *ui_Loading;
void ui_event_Image1( lv_event_t * e);
extern lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Home
void ui_Home_screen_init(void);
extern lv_obj_t *ui_Home;
void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label17;
void ui_event_Button10( lv_event_t * e);
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label19;
void ui_event_Button11( lv_event_t * e);
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Label20;
extern lv_obj_t *ui_Panel6;
void ui_event_Label14( lv_event_t * e);
extern lv_obj_t *ui_Label14;
void ui_event_Label18( lv_event_t * e);
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label28;
extern lv_obj_t *ui_beerPouringValue;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_totalBeerPoured;
extern lv_obj_t *ui_Label29;
extern lv_obj_t *ui_zAxisValue;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_temperatureValue;
// CUSTOM VARIABLES

// SCREEN: ui_WifiConfig
void ui_WifiConfig_screen_init(void);
extern lv_obj_t *ui_WifiConfig;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label4;
void ui_event_wifiNetworksAvailable( lv_event_t * e);
extern lv_obj_t *ui_wifiNetworksAvailable;
void ui_event_wifiName( lv_event_t * e);
extern lv_obj_t *ui_wifiName;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
void ui_event_wifiPassword( lv_event_t * e);
extern lv_obj_t *ui_wifiPassword;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label9;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_wifiLabelisConnected;
extern lv_obj_t *ui_wifiKeyboard;
void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label32;
// CUSTOM VARIABLES

// SCREEN: ui_QRCode
void ui_QRCode_screen_init(void);
extern lv_obj_t *ui_QRCode;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Image7;
void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern lv_obj_t *ui_Label15;
// CUSTOM VARIABLES

// SCREEN: ui_BeerPouring
void ui_BeerPouring_screen_init(void);
extern lv_obj_t *ui_BeerPouring;
extern lv_obj_t *ui_pourImage1;
void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Panel4;
void ui_event_Label24( lv_event_t * e);
extern lv_obj_t *ui_Label24;
// CUSTOM VARIABLES

// SCREEN: ui_KegConfig
void ui_KegConfig_screen_init(void);
extern lv_obj_t *ui_KegConfig;
extern lv_obj_t *ui_Label3;
void ui_event_Dropdown1( lv_event_t * e);
extern lv_obj_t *ui_Dropdown1;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Label8;
void ui_event_psiSlider( lv_event_t * e);
extern lv_obj_t *ui_psiSlider;
extern lv_obj_t *ui_psiValue;
extern lv_obj_t *ui_Panel2;
void ui_event_Label22( lv_event_t * e);
extern lv_obj_t *ui_Label22;
void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label27;
// CUSTOM VARIABLES

// SCREEN: ui_Configuration
void ui_Configuration_screen_init(void);
extern lv_obj_t *ui_Configuration;
extern lv_obj_t *ui_Panel7;
void ui_event_Label25( lv_event_t * e);
extern lv_obj_t *ui_Label25;
void ui_event_Label16( lv_event_t * e);
extern lv_obj_t *ui_Label16;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label23;
void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label26;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_beertaplogo_png);   // assets/beerTapLogo.png
LV_IMG_DECLARE( ui_img_qrcode_png);   // assets/qrCode.png
LV_IMG_DECLARE( ui_img_image1_png);   // assets/image1.png
LV_IMG_DECLARE( ui_img_image2_png);   // assets/image2.png
LV_IMG_DECLARE( ui_img_image3_png);   // assets/image3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
