// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_BeerPouring_screen_init(void)
{
ui_BeerPouring = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BeerPouring, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pourImage1 = lv_img_create(ui_BeerPouring);
lv_img_set_src(ui_pourImage1, &ui_img_image1_png);
lv_obj_set_width( ui_pourImage1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pourImage1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pourImage1, -1 );
lv_obj_set_y( ui_pourImage1, -79 );
lv_obj_set_align( ui_pourImage1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_pourImage1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_pourImage1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button3 = lv_btn_create(ui_BeerPouring);
lv_obj_set_width( ui_Button3, 300);
lv_obj_set_height( ui_Button3, 85);
lv_obj_set_x( ui_Button3, -6 );
lv_obj_set_y( ui_Button3, 236 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label13 = lv_label_create(ui_BeerPouring);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -12 );
lv_obj_set_y( ui_Label13, 235 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"Start");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_BeerPouring);
lv_obj_set_width( ui_Panel3, 100);
lv_obj_set_height( ui_Panel3, 50);
lv_obj_set_x( ui_Panel3, -44 );
lv_obj_set_y( ui_Panel3, -348 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel4 = lv_obj_create(ui_BeerPouring);
lv_obj_set_height( ui_Panel4, 75);
lv_obj_set_width( ui_Panel4, lv_pct(100));
lv_obj_set_x( ui_Panel4, lv_pct(0) );
lv_obj_set_y( ui_Panel4, lv_pct(-45) );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_BeerPouring);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label24, -197 );
lv_obj_set_y( ui_Label24, -362 );
lv_obj_set_align( ui_Label24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label24,"");
lv_obj_add_flag( ui_Label24, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label24, ui_event_Label24, LV_EVENT_ALL, NULL);

}
