// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void checkWifiStatusEvent(lv_event_t * e);
void selectedWifiSSID(lv_event_t * e);
void wifiName(lv_event_t * e);
void saveWifiConfiguration(lv_event_t * e);
void deleteWiFiConfig(lv_event_t * e);
void barrelSelected(lv_event_t * e);
void kegConfigSave(lv_event_t * e);
void WifiStatus(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
