// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void checkWifiStatusEvent(lv_event_t * e)
{
	// Your code here
}

void selectedWifiSSID(lv_event_t * e)
{
	// Your code here
}

void wifiName(lv_event_t * e)
{
	// Your code here
}

void saveWifiConfiguration(lv_event_t * e)
{
	// Your code here
}

void deleteWiFiConfig(lv_event_t * e)
{
	// Your code here
}

void barrelSelected(lv_event_t * e)
{
	// Your code here
}

void kegConfigSave(lv_event_t * e)
{
	// Your code here
}

void WifiStatus(lv_event_t * e)
{
	// Your code here
}
