// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_WifiConfig_screen_init(void)
{
ui_WifiConfig = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WifiConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -13 );
lv_obj_set_y( ui_Label2, -257 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Wifi Networks Available");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_WifiConfig);
lv_obj_set_height( ui_Panel1, 75);
lv_obj_set_width( ui_Panel1, lv_pct(100));
lv_obj_set_x( ui_Panel1, 1 );
lv_obj_set_y( ui_Panel1, lv_pct(-45) );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -102 );
lv_obj_set_y( ui_Label4, -362 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Wifi Status:");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiNetworksAvailable = lv_roller_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiNetworksAvailable, lv_pct(85));
lv_obj_set_height( ui_wifiNetworksAvailable, lv_pct(25));
lv_obj_set_x( ui_wifiNetworksAvailable, 2 );
lv_obj_set_y( ui_wifiNetworksAvailable, -106 );
lv_obj_set_align( ui_wifiNetworksAvailable, LV_ALIGN_CENTER );

ui_wifiName = lv_textarea_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiName, 260);
lv_obj_set_height( ui_wifiName, 70);
lv_obj_set_x( ui_wifiName, 68 );
lv_obj_set_y( ui_wifiName, 90 );
lv_obj_set_align( ui_wifiName, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wifiName,"Placeholder...");

ui_Label5 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, -154 );
lv_obj_set_y( ui_Label5, 94 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Wifi Name:");

ui_Label6 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -159 );
lv_obj_set_y( ui_Label6, 197 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Wifi Password");

ui_wifiPassword = lv_textarea_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiPassword, 292);
lv_obj_set_height( ui_wifiPassword, 70);
lv_obj_set_x( ui_wifiPassword, 66 );
lv_obj_set_y( ui_wifiPassword, 196 );
lv_obj_set_align( ui_wifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wifiPassword,"Placeholder...");

ui_Button1 = lv_btn_create(ui_WifiConfig);
lv_obj_set_height( ui_Button1, 70);
lv_obj_set_width( ui_Button1, lv_pct(30));
lv_obj_set_x( ui_Button1, 40 );
lv_obj_set_y( ui_Button1, 326 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, 42 );
lv_obj_set_y( ui_Label9, 326 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Save");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_WifiConfig);
lv_obj_set_width( ui_Button2, 164);
lv_obj_set_height( ui_Button2, 66);
lv_obj_set_x( ui_Button2, -131 );
lv_obj_set_y( ui_Button2, 326 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, -133 );
lv_obj_set_y( ui_Label10, 325 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Cancel");
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiLabelisConnected = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiLabelisConnected, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiLabelisConnected, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiLabelisConnected, 192 );
lv_obj_set_y( ui_wifiLabelisConnected, -358 );
lv_obj_set_align( ui_wifiLabelisConnected, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiLabelisConnected,"");
lv_obj_set_style_text_font(ui_wifiLabelisConnected, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiKeyboard = lv_keyboard_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiKeyboard, lv_pct(100));
lv_obj_set_height( ui_wifiKeyboard, lv_pct(20));
lv_obj_set_x( ui_wifiKeyboard, 0 );
lv_obj_set_y( ui_wifiKeyboard, 323 );
lv_obj_set_align( ui_wifiKeyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiKeyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_Button9 = lv_btn_create(ui_WifiConfig);
lv_obj_set_width( ui_Button9, 100);
lv_obj_set_height( ui_Button9, 73);
lv_obj_set_x( ui_Button9, 176 );
lv_obj_set_y( ui_Button9, 330 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label32 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, 176 );
lv_obj_set_y( ui_Label32, 330 );
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"     \nDelete");
lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_wifiNetworksAvailable, ui_event_wifiNetworksAvailable, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiName, ui_event_wifiName, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiPassword, ui_event_wifiPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_wifiKeyboard,ui_wifiPassword);
lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);

}
