// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Loading
void ui_Loading_screen_init(void);
void ui_event_Loading( lv_event_t * e);
lv_obj_t *ui_Loading;
void ui_event_Image1( lv_event_t * e);
lv_obj_t *ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Home
void ui_Home_screen_init(void);
lv_obj_t *ui_Home;
void ui_event_Button8( lv_event_t * e);
lv_obj_t *ui_Button8;
lv_obj_t *ui_Label17;
void ui_event_Button10( lv_event_t * e);
lv_obj_t *ui_Button10;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Panel6;
void ui_event_Label14( lv_event_t * e);
lv_obj_t *ui_Label14;
void ui_event_wifiLabelisConnected6( lv_event_t * e);
lv_obj_t *ui_wifiLabelisConnected6;
lv_obj_t *ui_Label28;
lv_obj_t *ui_beerPouringValue;
lv_obj_t *ui_Label29;
lv_obj_t *ui_zAxisValue;
lv_obj_t *ui_Label31;
lv_obj_t *ui_temperatureValue;
// CUSTOM VARIABLES

// SCREEN: ui_WifiConfig
void ui_WifiConfig_screen_init(void);
lv_obj_t *ui_WifiConfig;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label4;
void ui_event_wifiLabelisConnected3( lv_event_t * e);
lv_obj_t *ui_wifiLabelisConnected3;
void ui_event_wifiNetworksAvailable( lv_event_t * e);
lv_obj_t *ui_wifiNetworksAvailable;
lv_obj_t *ui_WifiNameLabel;
lv_obj_t *ui_Label6;
void ui_event_wifiPassword( lv_event_t * e);
lv_obj_t *ui_wifiPassword;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label9;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label10;
lv_obj_t *ui_wifiKeyboard;
void ui_event_Button9( lv_event_t * e);
lv_obj_t *ui_Button9;
lv_obj_t *ui_Label32;
lv_obj_t *ui_WifiNameValue;
lv_obj_t *ui_wifiLoadingSpinner;
void ui_event_wifiScanButton( lv_event_t * e);
lv_obj_t *ui_wifiScanButton;
lv_obj_t *ui_Label34;
// CUSTOM VARIABLES

// SCREEN: ui_QRCode
void ui_QRCode_screen_init(void);
void ui_event_QRCode( lv_event_t * e);
lv_obj_t *ui_QRCode;
lv_obj_t *ui_Panel5;
void ui_event_Label5( lv_event_t * e);
lv_obj_t *ui_Label5;
void ui_event_wifiLabelisConnected1( lv_event_t * e);
lv_obj_t *ui_wifiLabelisConnected1;
lv_obj_t *ui_QRImageLabel;
lv_obj_t *ui_QRCodeContainer;
// CUSTOM VARIABLES

// SCREEN: ui_BeerPouring
void ui_BeerPouring_screen_init(void);
lv_obj_t *ui_BeerPouring;
lv_obj_t *ui_Panel4;
void ui_event_Label24( lv_event_t * e);
lv_obj_t *ui_Label24;
void ui_event_wifiLabelisConnected5( lv_event_t * e);
lv_obj_t *ui_wifiLabelisConnected5;
lv_obj_t *ui_ozPouredLabel;
lv_obj_t *ui_ozPouredValue;
lv_obj_t *ui_Image4;
lv_obj_t *ui_beerPouringBar;
// CUSTOM VARIABLES

// SCREEN: ui_KegConfig
void ui_KegConfig_screen_init(void);
lv_obj_t *ui_KegConfig;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Dropdown1;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Label8;
void ui_event_psiSlider( lv_event_t * e);
lv_obj_t *ui_psiSlider;
lv_obj_t *ui_psiValue;
lv_obj_t *ui_Panel2;
void ui_event_Label22( lv_event_t * e);
lv_obj_t *ui_Label22;
void ui_event_Button7( lv_event_t * e);
lv_obj_t *ui_Button7;
lv_obj_t *ui_Label27;
// CUSTOM VARIABLES

// SCREEN: ui_Configuration
void ui_Configuration_screen_init(void);
lv_obj_t *ui_Configuration;
lv_obj_t *ui_Panel7;
void ui_event_Label25( lv_event_t * e);
lv_obj_t *ui_Label25;
void ui_event_wifiLabelisConnected4( lv_event_t * e);
lv_obj_t *ui_wifiLabelisConnected4;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label23;
void ui_event_Button6( lv_event_t * e);
lv_obj_t *ui_Button6;
lv_obj_t *ui_Label26;
void ui_event_screenBrightnessSlider( lv_event_t * e);
lv_obj_t *ui_screenBrightnessSlider;
lv_obj_t *ui_Label33;
lv_obj_t *ui_screenBrightnessLabelValue;
void ui_event_WiFiStatusButton( lv_event_t * e);
lv_obj_t *ui_WiFiStatusButton;
lv_obj_t *ui_WiFiStatusButtonLabel;
// CUSTOM VARIABLES

// SCREEN: ui_WiFiStatus
void ui_WiFiStatus_screen_init(void);
lv_obj_t *ui_WiFiStatus;
lv_obj_t *ui_Panel8;
void ui_event_HomeLabel( lv_event_t * e);
lv_obj_t *ui_HomeLabel;
void ui_event_wifiStatusIcon( lv_event_t * e);
lv_obj_t *ui_wifiStatusIcon;
lv_obj_t *ui_wifiSignalBar;
lv_obj_t *ui_Label11;
lv_obj_t *ui_wifiSignalValue;
lv_obj_t *ui_wifiIPValue;
lv_obj_t *ui_Label12;
lv_obj_t *ui_wifiSSIDValue;
lv_obj_t *ui_Label13;
void ui_event_wifiSpeedTestBtn( lv_event_t * e);
lv_obj_t *ui_wifiSpeedTestBtn;
lv_obj_t *ui_Label15;
lv_obj_t *ui_wifiSpeedValue;
lv_obj_t *ui_Label16;
lv_obj_t *ui_wifiLoadingSpinner1;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Loading( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 2000, &ui_Home_screen_init);
      _ui_screen_delete( &ui_Loading);
}
}

void ui_event_Image1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_Loading);
}
}

void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Loading, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Loading_screen_init);
      _ui_screen_delete( &ui_Home);
}
}

void ui_event_Button10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_QRCode, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_QRCode_screen_init);
      _ui_screen_delete( &ui_Home);
}
}

void ui_event_Label14( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Configuration, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Configuration_screen_init);
      _ui_screen_delete( &ui_Home);
}
}

void ui_event_wifiLabelisConnected6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      checkWifiStatus( e );
}
}

void ui_event_wifiLabelisConnected3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      checkWifiStatus( e );
}
}

void ui_event_wifiNetworksAvailable( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      selectedWifiSSID( e );
}
}

void ui_event_wifiPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_flag_modify( ui_wifiKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
}
}

void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      saveWifiConfiguration( e );
      _ui_screen_delete( &ui_WifiConfig);
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 500, &ui_Home_screen_init);
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_WifiConfig);
}
}

void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      deleteWiFiConfig( e );
}
}

void ui_event_wifiScanButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      start_wifi_scan( e );
}
}

void ui_event_QRCode( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      on_QRCodeScreen_load( e );
}
}

void ui_event_Label5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_QRCode);
}
}

void ui_event_wifiLabelisConnected1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      checkWifiStatus( e );
}
}

void ui_event_Label24( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_BeerPouring);
}
}

void ui_event_wifiLabelisConnected5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      checkWifiStatus( e );
}
}

void ui_event_psiSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_slider_set_text_value( ui_psiValue, target, "", "");
}
}

void ui_event_Label22( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_KegConfig);
}
}

void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      kegConfigSave( e );
}
}

void ui_event_Label25( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_KegConfig);
}
}

void ui_event_wifiLabelisConnected4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      checkWifiStatus( e );
}
}

void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_WifiConfig, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WifiConfig_screen_init);
      _ui_screen_delete( &ui_Configuration);
}
}

void ui_event_Button6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_KegConfig, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_KegConfig_screen_init);
      _ui_screen_delete( &ui_Configuration);
}
}

void ui_event_screenBrightnessSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_RELEASED) {
      changeScreenBrightness( e );
      _ui_slider_set_text_value( ui_screenBrightnessLabelValue, target, "", "");
}
}

void ui_event_WiFiStatusButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_WiFiStatus, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_WiFiStatus_screen_init);
      _ui_screen_delete( &ui_Configuration);
}
}

void ui_event_HomeLabel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_Home, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Home_screen_init);
      _ui_screen_delete( &ui_WiFiStatus);
}
}

void ui_event_wifiStatusIcon( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      event_wifiStatusIcon( e );
}
}

void ui_event_wifiSpeedTestBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      event_wifiSpeedTestBtn( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Loading_screen_init();
ui_Home_screen_init();
ui_WifiConfig_screen_init();
ui_QRCode_screen_init();
ui_BeerPouring_screen_init();
ui_KegConfig_screen_init();
ui_Configuration_screen_init();
ui_WiFiStatus_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Loading);
}
