// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_BatteryLux_screen_init(void)
{
ui_BatteryLux = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BatteryLux, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_batteryData = lv_label_create(ui_BatteryLux);
lv_obj_set_width( ui_batteryData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryData, 86 );
lv_obj_set_y( ui_batteryData, -188 );
lv_obj_set_align( ui_batteryData, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryData,"0");
lv_obj_set_style_text_font(ui_batteryData, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryLabel = lv_label_create(ui_BatteryLux);
lv_obj_set_width( ui_batteryLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryLabel, -92 );
lv_obj_set_y( ui_batteryLabel, -190 );
lv_obj_set_align( ui_batteryLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryLabel,"Battery:");
lv_obj_set_style_text_font(ui_batteryLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LuxLabel = lv_label_create(ui_BatteryLux);
lv_obj_set_width( ui_LuxLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LuxLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LuxLabel, -135 );
lv_obj_set_y( ui_LuxLabel, -75 );
lv_obj_set_align( ui_LuxLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LuxLabel,"LUX: ");

ui_luxData = lv_label_create(ui_BatteryLux);
lv_obj_set_width( ui_luxData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_luxData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_luxData, 52 );
lv_obj_set_y( ui_luxData, -73 );
lv_obj_set_align( ui_luxData, LV_ALIGN_CENTER );
lv_label_set_text(ui_luxData,"0");
lv_obj_set_style_text_font(ui_luxData, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_BatteryLux, ui_event_BatteryLux, LV_EVENT_ALL, NULL);

}
