// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_BeerPouring_screen_init(void)
{
ui_BeerPouring = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BeerPouring, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel4 = lv_obj_create(ui_BeerPouring);
lv_obj_set_height( ui_Panel4, 75);
lv_obj_set_width( ui_Panel4, lv_pct(100));
lv_obj_set_x( ui_Panel4, lv_pct(0) );
lv_obj_set_y( ui_Panel4, lv_pct(-45) );
lv_obj_set_align( ui_Panel4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label24 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_Label24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label24, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label24,"");
lv_obj_add_flag( ui_Label24, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiLabelisConnected5 = lv_label_create(ui_Panel4);
lv_obj_set_width( ui_wifiLabelisConnected5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiLabelisConnected5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiLabelisConnected5, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_wifiLabelisConnected5,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifiLabelisConnected5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_wifiLabelisConnected5,"");
lv_obj_set_style_text_font(ui_wifiLabelisConnected5, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ozPouredLabel = lv_label_create(ui_BeerPouring);
lv_obj_set_width( ui_ozPouredLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ozPouredLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ozPouredLabel, -163 );
lv_obj_set_y( ui_ozPouredLabel, -262 );
lv_obj_set_align( ui_ozPouredLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_ozPouredLabel,"OZ:");
lv_obj_set_style_text_font(ui_ozPouredLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ozPouredValue = lv_label_create(ui_BeerPouring);
lv_obj_set_width( ui_ozPouredValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ozPouredValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ozPouredValue, 110 );
lv_obj_set_y( ui_ozPouredValue, -261 );
lv_obj_set_align( ui_ozPouredValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_ozPouredValue,"0");
lv_obj_set_style_text_font(ui_ozPouredValue, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_BeerPouring);
lv_img_set_src(ui_Image4, &ui_img_beercan_png);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image4, 0 );
lv_obj_set_y( ui_Image4, 125 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image4,350);

ui_beerPouringBar = lv_bar_create(ui_BeerPouring);
lv_obj_set_width( ui_beerPouringBar, lv_pct(18));
lv_obj_set_height( ui_beerPouringBar, lv_pct(70));
lv_obj_set_x( ui_beerPouringBar, 0 );
lv_obj_set_y( ui_beerPouringBar, 123 );
lv_obj_set_align( ui_beerPouringBar, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_beerPouringBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_beerPouringBar, lv_color_hex(0xDFDFDF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_beerPouringBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_beerPouringBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_beerPouringBar, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_beerPouringBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_beerPouringBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_beerPouringBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_beerPouringBar, lv_color_hex(0x8A8D17), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_beerPouringBar, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_beerPouringBar, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Label24, ui_event_Label24, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiLabelisConnected5, ui_event_wifiLabelisConnected5, LV_EVENT_ALL, NULL);

}
