// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button10 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button10, lv_pct(60));
lv_obj_set_height( ui_Button10, lv_pct(10));
lv_obj_set_y( ui_Button10, 176 );
lv_obj_set_x( ui_Button10, lv_pct(0) );
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label19 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 0 );
lv_obj_set_y( ui_Label19, 173 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"QR Code");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel6 = lv_obj_create(ui_Home);
lv_obj_set_height( ui_Panel6, 75);
lv_obj_set_width( ui_Panel6, lv_pct(100));
lv_obj_set_x( ui_Panel6, 0 );
lv_obj_set_y( ui_Panel6, lv_pct(-45) );
lv_obj_set_align( ui_Panel6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label14, LV_ALIGN_LEFT_MID );
lv_obj_set_flex_flow(ui_Label14,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Label14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Label14,"");
lv_obj_add_flag( ui_Label14, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiLabelisConnected6 = lv_label_create(ui_Panel6);
lv_obj_set_width( ui_wifiLabelisConnected6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiLabelisConnected6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiLabelisConnected6, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_wifiLabelisConnected6,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifiLabelisConnected6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_wifiLabelisConnected6,"");
lv_obj_set_style_text_font(ui_wifiLabelisConnected6, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label28 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, -85 );
lv_obj_set_y( ui_Label28, -191 );
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"Beer Pouring:");
lv_obj_set_style_text_align(ui_Label28, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_beerPouringValue = lv_label_create(ui_Home);
lv_obj_set_width( ui_beerPouringValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_beerPouringValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_beerPouringValue, 145 );
lv_obj_set_y( ui_beerPouringValue, -188 );
lv_obj_set_align( ui_beerPouringValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_beerPouringValue,"No");
lv_obj_set_style_text_align(ui_beerPouringValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_beerPouringValue, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label29 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label29, -145 );
lv_obj_set_y( ui_Label29, -265 );
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"Z Axis: ");
lv_obj_set_style_text_align(ui_Label29, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_zAxisValue = lv_label_create(ui_Home);
lv_obj_set_width( ui_zAxisValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_zAxisValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_zAxisValue, -5 );
lv_obj_set_y( ui_zAxisValue, -264 );
lv_obj_set_align( ui_zAxisValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_zAxisValue,"0");
lv_obj_set_style_text_align(ui_zAxisValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_zAxisValue, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label31 = lv_label_create(ui_Home);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, -162 );
lv_obj_set_y( ui_Label31, -119 );
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"Temp:");
lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temperatureValue = lv_label_create(ui_Home);
lv_obj_set_width( ui_temperatureValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperatureValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temperatureValue, -17 );
lv_obj_set_y( ui_temperatureValue, -111 );
lv_obj_set_align( ui_temperatureValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperatureValue,"0");
lv_obj_set_style_text_align(ui_temperatureValue, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temperatureValue, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Home);
lv_obj_set_width( ui_Button3, 295);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, 5 );
lv_obj_set_y( ui_Button3, 36 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Video Animation");

lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label14, ui_event_Label14, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiLabelisConnected6, ui_event_wifiLabelisConnected6, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);

}
