// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_KegConfig_screen_init(void)
{
ui_KegConfig = lv_obj_create(NULL);
lv_obj_clear_flag( ui_KegConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_KegConfig);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -2 );
lv_obj_set_y( ui_Label3, -260 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Keg Configuration");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Dropdown1 = lv_dropdown_create(ui_KegConfig);
lv_dropdown_set_options( ui_Dropdown1, "1/6 Barrel\n50 Liter Barrel\n1/4 Barrel (Slim 30)\n1/4 Barrel (Standard)\n1/2 Barrel" );
lv_obj_set_width( ui_Dropdown1, 270);
lv_obj_set_height( ui_Dropdown1, 50);
lv_obj_set_x( ui_Dropdown1, 53 );
lv_obj_set_y( ui_Dropdown1, -125 );
lv_obj_set_align( ui_Dropdown1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Label7 = lv_label_create(ui_KegConfig);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, -172 );
lv_obj_set_y( ui_Label7, -128 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Size:");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_KegConfig);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -167 );
lv_obj_set_y( ui_Label8, 22 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"PSI: ");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_psiSlider = lv_slider_create(ui_KegConfig);
lv_slider_set_range(ui_psiSlider, 5,80);
lv_slider_set_value( ui_psiSlider, 15, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_psiSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_psiSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_psiSlider, 150);
lv_obj_set_height( ui_psiSlider, 30);
lv_obj_set_x( ui_psiSlider, 78 );
lv_obj_set_y( ui_psiSlider, 25 );
lv_obj_set_align( ui_psiSlider, LV_ALIGN_CENTER );

ui_psiValue = lv_label_create(ui_KegConfig);
lv_obj_set_width( ui_psiValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_psiValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_psiValue, -61 );
lv_obj_set_y( ui_psiValue, 23 );
lv_obj_set_align( ui_psiValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_psiValue,"12");
lv_obj_set_style_text_font(ui_psiValue, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_KegConfig);
lv_obj_set_height( ui_Panel2, 74);
lv_obj_set_width( ui_Panel2, lv_pct(100));
lv_obj_set_x( ui_Panel2, lv_pct(0) );
lv_obj_set_y( ui_Panel2, lv_pct(-45) );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label22 = lv_label_create(ui_KegConfig);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label22, -196 );
lv_obj_set_y( ui_Label22, -359 );
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"");
lv_obj_add_flag( ui_Label22, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_btn_create(ui_KegConfig);
lv_obj_set_width( ui_Button7, 265);
lv_obj_set_height( ui_Button7, 92);
lv_obj_set_x( ui_Button7, -2 );
lv_obj_set_y( ui_Button7, 302 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label27 = lv_label_create(ui_KegConfig);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label27, -6 );
lv_obj_set_y( ui_Label27, 299 );
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27," Save");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_psiSlider, ui_event_psiSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Label22, ui_event_Label22, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}
