// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_QRCode_screen_init(void)
{
ui_QRCode = lv_obj_create(NULL);
lv_obj_clear_flag( ui_QRCode, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel5 = lv_obj_create(ui_QRCode);
lv_obj_set_height( ui_Panel5, 75);
lv_obj_set_width( ui_Panel5, lv_pct(100));
lv_obj_set_x( ui_Panel5, lv_pct(0) );
lv_obj_set_y( ui_Panel5, lv_pct(-45) );
lv_obj_set_align( ui_Panel5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Label5,"");
lv_obj_add_flag( ui_Label5, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiLabelisConnected1 = lv_label_create(ui_Panel5);
lv_obj_set_width( ui_wifiLabelisConnected1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiLabelisConnected1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiLabelisConnected1, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_wifiLabelisConnected1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifiLabelisConnected1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_wifiLabelisConnected1,"");
lv_obj_set_style_text_font(ui_wifiLabelisConnected1, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_QRImageLabel = lv_label_create(ui_QRCode);
lv_obj_set_width( ui_QRImageLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_QRImageLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_QRImageLabel, 0 );
lv_obj_set_y( ui_QRImageLabel, -263 );
lv_obj_set_align( ui_QRImageLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_QRImageLabel,"");
lv_obj_set_style_text_font(ui_QRImageLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_QRCodeContainer = lv_obj_create(ui_QRCode);
lv_obj_remove_style_all(ui_QRCodeContainer);
lv_obj_set_width( ui_QRCodeContainer, 480);
lv_obj_set_height( ui_QRCodeContainer, 560);
lv_obj_set_x( ui_QRCodeContainer, -1 );
lv_obj_set_y( ui_QRCodeContainer, 94 );
lv_obj_set_align( ui_QRCodeContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_QRCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_Label5, ui_event_Label5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiLabelisConnected1, ui_event_wifiLabelisConnected1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_QRCode, ui_event_QRCode, LV_EVENT_ALL, NULL);

}
