// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_videoAnimation_screen_init(void)
{
ui_videoAnimation = lv_obj_create(NULL);
lv_obj_clear_flag( ui_videoAnimation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_videoContainer = lv_obj_create(ui_videoAnimation);
lv_obj_remove_style_all(ui_videoContainer);
lv_obj_set_width( ui_videoContainer, lv_pct(100));
lv_obj_set_height( ui_videoContainer, lv_pct(100));
lv_obj_set_align( ui_videoContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_videoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
