// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_WiFiStatus_screen_init(void)
{
ui_WiFiStatus = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WiFiStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel8 = lv_obj_create(ui_WiFiStatus);
lv_obj_set_height( ui_Panel8, 75);
lv_obj_set_width( ui_Panel8, lv_pct(100));
lv_obj_set_x( ui_Panel8, lv_pct(0) );
lv_obj_set_y( ui_Panel8, lv_pct(-45) );
lv_obj_set_align( ui_Panel8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeLabel = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_HomeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HomeLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HomeLabel,"");
lv_obj_add_flag( ui_HomeLabel, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_set_style_text_font(ui_HomeLabel, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiStatusIcon = lv_label_create(ui_Panel8);
lv_obj_set_width( ui_wifiStatusIcon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiStatusIcon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiStatusIcon, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_wifiStatusIcon,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifiStatusIcon, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_wifiStatusIcon,"");
lv_obj_set_style_text_font(ui_wifiStatusIcon, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiSignalBar = lv_bar_create(ui_WiFiStatus);
lv_bar_set_value(ui_wifiSignalBar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_wifiSignalBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_wifiSignalBar, 150);
lv_obj_set_height( ui_wifiSignalBar, 82);
lv_obj_set_x( ui_wifiSignalBar, 139 );
lv_obj_set_y( ui_wifiSignalBar, -217 );
lv_obj_set_align( ui_wifiSignalBar, LV_ALIGN_CENTER );

ui_Label11 = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label11, -143 );
lv_obj_set_y( ui_Label11, -214 );
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"WiFi \nSignal:");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiSignalValue = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_wifiSignalValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiSignalValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiSignalValue, -11 );
lv_obj_set_y( ui_wifiSignalValue, -206 );
lv_obj_set_align( ui_wifiSignalValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiSignalValue,"0");
lv_obj_set_style_text_font(ui_wifiSignalValue, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiIPValue = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_wifiIPValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiIPValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiIPValue, 46 );
lv_obj_set_y( ui_wifiIPValue, -58 );
lv_obj_set_align( ui_wifiIPValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiIPValue,"0.0.0.0");

ui_Label12 = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -116 );
lv_obj_set_y( ui_Label12, -59 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"IP Address:");

ui_wifiSSIDValue = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_wifiSSIDValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiSSIDValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiSSIDValue, 45 );
lv_obj_set_y( ui_wifiSSIDValue, -5 );
lv_obj_set_align( ui_wifiSSIDValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiSSIDValue,"NULL");

ui_Label13 = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -114 );
lv_obj_set_y( ui_Label13, 6 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"SSID:");

ui_wifiSpeedTestBtn = lv_btn_create(ui_WiFiStatus);
lv_obj_set_width( ui_wifiSpeedTestBtn, 100);
lv_obj_set_height( ui_wifiSpeedTestBtn, 50);
lv_obj_set_x( ui_wifiSpeedTestBtn, -18 );
lv_obj_set_y( ui_wifiSpeedTestBtn, 89 );
lv_obj_set_align( ui_wifiSpeedTestBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiSpeedTestBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifiSpeedTestBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label15 = lv_label_create(ui_wifiSpeedTestBtn);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Speed Test");

ui_wifiSpeedValue = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_wifiSpeedValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiSpeedValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiSpeedValue, 65 );
lv_obj_set_y( ui_wifiSpeedValue, 229 );
lv_obj_set_align( ui_wifiSpeedValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiSpeedValue,"0KB");

ui_Label16 = lv_label_create(ui_WiFiStatus);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, -139 );
lv_obj_set_y( ui_Label16, 225 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"Speed Value");

ui_wifiLoadingSpinner1 = lv_spinner_create(ui_WiFiStatus,1000,90);
lv_obj_set_width( ui_wifiLoadingSpinner1, lv_pct(50));
lv_obj_set_height( ui_wifiLoadingSpinner1, lv_pct(31));
lv_obj_set_align( ui_wifiLoadingSpinner1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiLoadingSpinner1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_wifiLoadingSpinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_add_event_cb(ui_HomeLabel, ui_event_HomeLabel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiStatusIcon, ui_event_wifiStatusIcon, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiSpeedTestBtn, ui_event_wifiSpeedTestBtn, LV_EVENT_ALL, NULL);

}
