// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_WifiConfig_screen_init(void)
{
ui_WifiConfig = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WifiConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -121 );
lv_obj_set_y( ui_Label2, -273 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Networks Available");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel1 = lv_obj_create(ui_WifiConfig);
lv_obj_set_height( ui_Panel1, 75);
lv_obj_set_width( ui_Panel1, lv_pct(100));
lv_obj_set_x( ui_Panel1, 1 );
lv_obj_set_y( ui_Panel1, lv_pct(-45) );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x5E5F5F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_flow(ui_Label4,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Label4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_Label4,"Wifi Status:");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiLabelisConnected3 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_wifiLabelisConnected3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiLabelisConnected3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiLabelisConnected3, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_wifiLabelisConnected3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_wifiLabelisConnected3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_wifiLabelisConnected3,"");
lv_obj_set_style_text_font(ui_wifiLabelisConnected3, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiNetworksAvailable = lv_roller_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiNetworksAvailable, lv_pct(85));
lv_obj_set_height( ui_wifiNetworksAvailable, lv_pct(13));
lv_obj_set_x( ui_wifiNetworksAvailable, 0 );
lv_obj_set_y( ui_wifiNetworksAvailable, -162 );
lv_obj_set_align( ui_wifiNetworksAvailable, LV_ALIGN_CENTER );

ui_WifiNameLabel = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_WifiNameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiNameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiNameLabel, -156 );
lv_obj_set_y( ui_WifiNameLabel, -81 );
lv_obj_set_align( ui_WifiNameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiNameLabel,"Wifi Name:");

ui_Label6 = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, -158 );
lv_obj_set_y( ui_Label6, -34 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Wifi Password");

ui_wifiPassword = lv_textarea_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiPassword, 292);
lv_obj_set_height( ui_wifiPassword, 39);
lv_obj_set_x( ui_wifiPassword, 68 );
lv_obj_set_y( ui_wifiPassword, -29 );
lv_obj_set_align( ui_wifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wifiPassword,"WiFi Password");
lv_textarea_set_password_mode(ui_wifiPassword, true);

ui_Button1 = lv_btn_create(ui_WifiConfig);
lv_obj_set_height( ui_Button1, 70);
lv_obj_set_width( ui_Button1, lv_pct(40));
lv_obj_set_x( ui_Button1, 99 );
lv_obj_set_y( ui_Button1, 283 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_Button1);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Save");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button2 = lv_btn_create(ui_WifiConfig);
lv_obj_set_height( ui_Button2, 70);
lv_obj_set_width( ui_Button2, lv_pct(40));
lv_obj_set_x( ui_Button2, -110 );
lv_obj_set_y( ui_Button2, 282 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label10 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"Cancel");
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiKeyboard = lv_keyboard_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiKeyboard, lv_pct(100));
lv_obj_set_height( ui_wifiKeyboard, lv_pct(26));
lv_obj_set_x( ui_wifiKeyboard, 4 );
lv_obj_set_y( ui_wifiKeyboard, 115 );
lv_obj_set_align( ui_wifiKeyboard, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiKeyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

ui_Button9 = lv_btn_create(ui_WifiConfig);
lv_obj_set_width( ui_Button9, 301);
lv_obj_set_height( ui_Button9, 47);
lv_obj_set_x( ui_Button9, -9 );
lv_obj_set_y( ui_Button9, 370 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFD0303), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label32 = lv_label_create(ui_Button9);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32," Delete Current Config");
lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiNameValue = lv_label_create(ui_WifiConfig);
lv_obj_set_width( ui_WifiNameValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiNameValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiNameValue, 29 );
lv_obj_set_y( ui_WifiNameValue, -81 );
lv_obj_set_align( ui_WifiNameValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_WifiNameValue,"PENDING_SETUP");
lv_obj_set_style_text_font(ui_WifiNameValue, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiLoadingSpinner = lv_spinner_create(ui_WifiConfig,1000,90);
lv_obj_set_width( ui_wifiLoadingSpinner, lv_pct(50));
lv_obj_set_height( ui_wifiLoadingSpinner, lv_pct(30));
lv_obj_set_align( ui_wifiLoadingSpinner, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiLoadingSpinner, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_wifiLoadingSpinner, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_wifiScanButton = lv_btn_create(ui_WifiConfig);
lv_obj_set_width( ui_wifiScanButton, 220);
lv_obj_set_height( ui_wifiScanButton, 50);
lv_obj_set_x( ui_wifiScanButton, 114 );
lv_obj_set_y( ui_wifiScanButton, -276 );
lv_obj_set_align( ui_wifiScanButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiScanButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifiScanButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label34 = lv_label_create(ui_wifiScanButton);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, 6 );
lv_obj_set_y( ui_Label34, 1 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"Scan WiFi");
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_wifiLabelisConnected3, ui_event_wifiLabelisConnected3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiNetworksAvailable, ui_event_wifiNetworksAvailable, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiPassword, ui_event_wifiPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_wifiKeyboard,ui_wifiPassword);
lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_wifiScanButton, ui_event_wifiScanButton, LV_EVENT_ALL, NULL);

}
